[project]
name = "wifi-auto-authentication"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.2"
dependencies = [
    "python-dotenv>=1.1.1",
    "selenium>=4.35.0",
]
